### ISSUE TITLE
marian-conv options are displayed incorrectly

### ISSUE THREAD

**Issue by snukky** [marian-nmt/marian-nmt.github.io#42] opened 2022-02-05 19:27 UTC
Probably some string in the help messages interferes with the markdown syntax: https://marian-nmt.github.io/docs/cmd/marian-conv/

**Comment by graemenail** [comment] 2022-02-06 17:57
My _guess_ is that the description of `marian-conv` exceeding one line is the cause; should probably replace the bash script with something in Python. I'll have a proper look tomorrow.

**Comment by graemenail** [comment] 2022-02-07 13:09
Closed by #43.

Closing manually because we're not on the default branch.
> When you merge a linked pull request into the default branch of a repository, its linked issue is automatically closed.

**Closed as completed by graemenail** 2022-02-07 13:09 UTC
Labels: bug
